//
// Created by Michael Lewis on 10/28/23.
//

#ifndef MULTI_THREADED_ALGORITHMIC_TRADING_SYSTEM_STRATEGYCONFIGMANAGER_HPP
#define MULTI_THREADED_ALGORITHMIC_TRADING_SYSTEM_STRATEGYCONFIGMANAGER_HPP

namespace BeaconTech::Strategies
{

    class StrategyConfigManager
    {

    };

} // BeaconTech::Strategies

#endif //MULTI_THREADED_ALGORITHMIC_TRADING_SYSTEM_STRATEGYCONFIGMANAGER_HPP
